onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /testbench_htm_core/Core/Reset
add wave -noupdate /testbench_htm_core/Core/Clock
add wave -noupdate /testbench_htm_core/Core/TransactionStatus
add wave -noupdate /testbench_htm_core/Core/Action
add wave -noupdate /testbench_htm_core/Core/CU/CurrStateIs
add wave -noupdate /testbench_htm_core/Core/CUStatus
add wave -noupdate /testbench_htm_core/Core/CU/BuffStatus
add wave -noupdate /testbench_htm_core/Core/ConfBufStatus
add wave -noupdate /testbench_htm_core/Core/MemAddress
add wave -noupdate /testbench_htm_core/Core/QueueStatus
add wave -noupdate /testbench_htm_core/Core/Buff/QueueReturn
add wave -noupdate /testbench_htm_core/Core/Buff/MemoryAddr
add wave -noupdate /testbench_htm_core/Core/Buff/MemoryData
add wave -noupdate /testbench_htm_core/Core/TransactionID
add wave -noupdate /testbench_htm_core/Core/Commit/TrID
add wave -noupdate -subitemconfig {/testbench_htm_core/Core/Commit/MemStorage(2) -expand /testbench_htm_core/Core/Commit/MemStorage(1) -expand} /testbench_htm_core/Core/Commit/MemStorage
add wave -noupdate /testbench_htm_core/Core/Data
add wave -noupdate /testbench_htm_core/Core/ProcID
add wave -noupdate /testbench_htm_core/Core/IntAbortStatus
add wave -noupdate /testbench_htm_core/Core/ConfBufMode
add wave -noupdate /testbench_htm_core/Core/ConfBufTrID
add wave -noupdate /testbench_htm_core/Core/QueueMode
add wave -noupdate /testbench_htm_core/Core/BuffStatus
add wave -noupdate /testbench_htm_core/Core/QueueReturn
add wave -noupdate /testbench_htm_core/Core/MemoryAddr
add wave -noupdate /testbench_htm_core/Core/MemoryData
add wave -noupdate /testbench_htm_core/Core/CBProcStatus
add wave -noupdate /testbench_htm_core/Core/CU/Action
add wave -noupdate /testbench_htm_core/Core/CU/IntAbortStatus
add wave -noupdate /testbench_htm_core/Core/CU/CUStatus
add wave -noupdate /testbench_htm_core/Core/CU/Reset
add wave -noupdate /testbench_htm_core/Core/CU/Clock
add wave -noupdate /testbench_htm_core/Core/Buff/MemAddress
add wave -noupdate /testbench_htm_core/Core/Buff/Data
add wave -noupdate /testbench_htm_core/Core/Buff/ProcID
add wave -noupdate /testbench_htm_core/Core/Buff/TransactionID
add wave -noupdate /testbench_htm_core/Core/Buff/CUStatus
add wave -noupdate /testbench_htm_core/Core/Buff/ConfBufMode
add wave -noupdate /testbench_htm_core/Core/Buff/ConfBufTrID
add wave -noupdate /testbench_htm_core/Core/Buff/ConfBufStatus
add wave -noupdate /testbench_htm_core/Core/Buff/CBProcStatus
add wave -noupdate /testbench_htm_core/Core/Buff/QueueMode
add wave -noupdate /testbench_htm_core/Core/Buff/QueueStatus
add wave -noupdate /testbench_htm_core/Core/Buff/BuffStatus
add wave -noupdate /testbench_htm_core/Core/Buff/Reset
add wave -noupdate /testbench_htm_core/Core/Buff/Clock
add wave -noupdate /testbench_htm_core/Core/Buff/MemBuffer
add wave -noupdate /testbench_htm_core/Core/Commit/Mode
add wave -noupdate /testbench_htm_core/Core/Commit/Addr
add wave -noupdate /testbench_htm_core/Core/Commit/FIFOStatus
add wave -noupdate /testbench_htm_core/Core/Commit/Ret
add wave -noupdate /testbench_htm_core/Core/Commit/Reset
add wave -noupdate /testbench_htm_core/Core/Commit/Clock
add wave -noupdate /testbench_htm_core/Core/Abort/TrID
add wave -noupdate /testbench_htm_core/Core/Abort/Mode
add wave -noupdate /testbench_htm_core/Core/Abort/Status
add wave -noupdate /testbench_htm_core/Core/Abort/ProcStatus
add wave -noupdate /testbench_htm_core/Core/Abort/IntAbortStatus
add wave -noupdate /testbench_htm_core/Core/Abort/Reset
add wave -noupdate /testbench_htm_core/Core/Abort/ConflictFlag
add wave -noupdate /testbench_htm_core/Core/Memory/Addr
add wave -noupdate /testbench_htm_core/Core/Memory/Data
add wave -noupdate /testbench_htm_core/Core/Memory/Reset
add wave -noupdate /testbench_htm_core/Core/Memory/Clock
add wave -noupdate /testbench_htm_core/Core/Memory/Mem
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {224600 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {304500 ps}
